/**
 * NEXUS AI — Production-Grade Content Substance & Placeholder Detector
 *
 * Provides deterministic, reusable AST & textual analysis over generated web artifacts.
 * Prevents empty skeletons, comment-only containers, unresolved generation tokens,
 * and generic fallback templates from masquerading as successful task completions.
 */

export interface PlaceholderDetectionResult {
  hasPlaceholders: boolean;
  reasons: string[];
  placeholderMatches: string[];
}

export interface SkeletonDetectionResult {
  isSkeleton: boolean;
  totalContainers: number;
  emptyOrCommentOnlyContainers: number;
  skeletonSectionNames: string[];
  reasons: string[];
}

export interface ContentVerificationResult {
  valid: boolean;
  errorCategory?: string;
  reason?: string;
  visibleTextLength?: number;
  detectedBrand?: string;
  foundBrand?: boolean;
  missingSections?: string[];
  skeletonSections?: string[];
}

// ---------------------------------------------------------------------------
// 1. Text & HTML Sanitization Helpers
// ---------------------------------------------------------------------------

/**
 * Extracts pure visible text rendered to the user from HTML source.
 * Strips scripts, styles, noscript, svg, comments, and all HTML tags.
 */
export function extractVisibleText(htmlContent: string): string {
  if (!htmlContent) return '';

  return htmlContent
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, ' ')
    .replace(/<style\b[^<]*(?:(?!<\/style>)<[^<]*)*<\/style>/gi, ' ')
    .replace(/<noscript\b[^<]*(?:(?!<\/noscript>)<[^<]*)*<\/noscript>/gi, ' ')
    .replace(/<svg\b[^<]*(?:(?!<\/svg>)<[^<]*)*<\/svg>/gi, ' ')
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>')
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'")
    .replace(/&copy;/gi, '©')
    .replace(/\s+/g, ' ')
    .trim();
}

// ---------------------------------------------------------------------------
// 2. Unresolved Placeholder & Token Detector
// ---------------------------------------------------------------------------

/**
 * Detects unresolved placeholder comments, TODO/TBD markers, and generic templates.
 */
export function detectPlaceholders(htmlContent: string, taskGoal?: string): PlaceholderDetectionResult {
  const reasons: string[] = [];
  const matches: string[] = [];

  const lowerGoal = (taskGoal || '').toLowerCase();

  // Pattern 1: Placeholder comments like <!-- Hero Content -->, <!-- Features Content -->, <!-- Content -->, <!-- TODO -->
  const commentPlaceholderRegex = /<!--\s*([a-zA-Z0-9_\s-]*?(?:\bcontent\b|\btodo\b|\btbd\b|\bplaceholder\b|insert\s+\w+\s+here|your\s+content)[a-zA-Z0-9_\s-]*?)\s*-->/gi;
  let commentMatch: RegExpExecArray | null;
  while ((commentMatch = commentPlaceholderRegex.exec(htmlContent)) !== null) {
    const matchedText = commentMatch[0].trim();
    matches.push(matchedText);
    reasons.push(`Unresolved placeholder comment detected: "${matchedText}"`);
  }

  // Pattern 2: Explicit placeholder text tokens inside visible body text
  const bodyMatch = htmlContent.match(/<body\b[^>]*>([\s\S]*?)<\/body>/i);
  const bodyHtml = bodyMatch ? bodyMatch[1] : htmlContent;
  const visibleBodyText = extractVisibleText(bodyHtml);

  const textTokenPatterns: Array<{ regex: RegExp; name: string; target: 'visible' | 'raw'; allowIfInGoal?: boolean }> = [
    { regex: /\bTODO\b/i, name: 'TODO token', target: 'visible' },
    { regex: /\bTBD\b/i, name: 'TBD token', target: 'visible' },
    { regex: /\bPLACEHOLDER\b/i, name: 'PLACEHOLDER token', target: 'visible' },
    { regex: /\bYOUR\s+CONTENT\s+HERE\b/i, name: 'YOUR CONTENT HERE token', target: 'visible' },
    { regex: /\bINSERT\s+[\w\s]+\s+HERE\b/i, name: 'INSERT ... HERE token', target: 'visible' },
    { regex: /\bREPLACE\s+WITH\s+[\w\s]+\b/i, name: 'REPLACE WITH ... token', target: 'visible' },
    { regex: /\bLorem\s+ipsum\s+dolor\b/i, name: 'Lorem ipsum placeholder text', target: 'visible' },
    {
      regex: /Generated\s+by\s+NEXUS\s+AI\s+Agent/i,
      name: 'Generic fallback marker "Generated by NEXUS AI Agent"',
      target: 'raw',
      allowIfInGoal: lowerGoal.includes('nexus ai agent') || lowerGoal.includes('nexus web application'),
    },
    {
      regex: /NEXUS\s+Web\s+Application/i,
      name: 'Generic fallback title "NEXUS Web Application"',
      target: 'raw',
      allowIfInGoal: lowerGoal.includes('nexus web application'),
    },
  ];

  for (const { regex, name, target, allowIfInGoal } of textTokenPatterns) {
    if (allowIfInGoal) continue;
    const searchTarget = target === 'visible' ? visibleBodyText : htmlContent;
    const match = searchTarget.match(regex);
    if (match) {
      matches.push(match[0]);
      reasons.push(`Unresolved generation marker detected: ${name} ("${match[0]}")`);
    }
  }

  return {
    hasPlaceholders: matches.length > 0,
    reasons,
    placeholderMatches: matches,
  };
}

// ---------------------------------------------------------------------------
// 3. Structural Skeleton & Empty Container Detector
// ---------------------------------------------------------------------------

/**
 * Analyzes semantic container elements (<section>, <header>, <nav>, <footer>, <main>, <article>, and major section <div>s)
 * to detect empty shells or comment-only skeletons.
 */
export function detectSkeletonContainers(htmlContent: string): SkeletonDetectionResult {
  const reasons: string[] = [];
  const skeletonSectionNames: string[] = [];

  // Decorative element patterns that are legitimately empty in modern CSS (glows, overlays, bars, etc.)
  const decorativePattern = /(?:bg-glow|bg-grid|overlay|backdrop|particle|spacer|divider|\bbar\b|toggle-bar|separator|decoration|blur|halo|beam|mesh|glow|circle|dot|blob|star|spinner)/i;

  // 1. Check all <section ...>...</section> tags (sections should never be empty or comment-only in complete projects)
  const sectionRegex = /<section\b([^>]*)>([\s\S]*?)<\/section>/gi;
  let totalSections = 0;
  let emptyOrCommentOnlySections = 0;

  let sMatch: RegExpExecArray | null;
  while ((sMatch = sectionRegex.exec(htmlContent)) !== null) {
    totalSections++;
    const attrs = sMatch[1];
    const innerContent = sMatch[2] || '';

    const idMatch = attrs.match(/id=["']([^"']+)["']/i);
    const classMatch = attrs.match(/class=["']([^"']+)["']/i);
    const identifier = idMatch
      ? `#${idMatch[1]}`
      : classMatch
      ? `.${classMatch[1].split(/\s+/)[0]}`
      : `section[${totalSections}]`;

    const trimmedInner = innerContent.trim();
    const visibleText = extractVisibleText(innerContent);
    const isCommentOnly = trimmedInner.length > 0 && /^(\s*<!--[\s\S]*?-->\s*)+$/i.test(trimmedInner);
    const isEmpty = trimmedInner.length === 0;
    const hasVisualElements = /<(?:img|svg|input|button|canvas|video|audio|iframe|form|ul|ol|table|h[1-6]|p)\b/i.test(innerContent);

    if (isCommentOnly || (isEmpty && !decorativePattern.test(identifier)) || (visibleText.length === 0 && !hasVisualElements && !decorativePattern.test(identifier))) {
      emptyOrCommentOnlySections++;
      skeletonSectionNames.push(identifier);
      if (isCommentOnly) {
        reasons.push(`Section <${identifier}> contains only HTML comments without real implementation.`);
      } else if (isEmpty) {
        reasons.push(`Section <${identifier}> is completely empty.`);
      } else {
        reasons.push(`Section <${identifier}> contains no visible text or UI elements.`);
      }
    }
  }

  // 2. Check major content <div id="..." or class="..."> containing comment-only placeholders like <!-- Hero Content -->
  const divCommentRegex = /<div\b[^>]*?(?:id|class)=["']([^"']+)["'][^>]*>\s*<!--\s*([a-zA-Z0-9_\s-]+?)\s*(?:Content|Section|Placeholder)?\s*-->\s*<\/div>/gi;
  let dMatch: RegExpExecArray | null;
  while ((dMatch = divCommentRegex.exec(htmlContent)) !== null) {
    const divIdOrClass = dMatch[1];
    const placeholderText = dMatch[2];
    const identifier = `div.${divIdOrClass}`;
    if (!skeletonSectionNames.includes(identifier)) {
      skeletonSectionNames.push(identifier);
      emptyOrCommentOnlySections++;
      reasons.push(`Container <${identifier}> contains only placeholder comment '<!-- ${placeholderText} -->'`);
    }
  }

  // 3. Determine if document is an incomplete skeleton
  const totalContainers = totalSections + (skeletonSectionNames.length - emptyOrCommentOnlySections);
  const isSkeleton =
    skeletonSectionNames.length > 0 &&
    (emptyOrCommentOnlySections >= 2 ||
      (totalSections > 0 && emptyOrCommentOnlySections / totalSections >= 0.3) ||
      reasons.some((r) => r.includes('contains only HTML comments') || r.includes('placeholder comment')));

  return {
    isSkeleton,
    totalContainers: Math.max(totalContainers, totalSections),
    emptyOrCommentOnlyContainers: emptyOrCommentOnlySections,
    skeletonSectionNames,
    reasons,
  };
}

// ---------------------------------------------------------------------------
// 4. Request-Aware Section & Brand Substance Verifier
// ---------------------------------------------------------------------------

/**
 * Extracts candidate brand / proper project names from the task goal.
 */
export function extractBrandCandidates(taskGoal: string): string[] {
  const stopWords = new Set([
    'a', 'an', 'the', 'and', 'or', 'for', 'with', 'to', 'of', 'in', 'on', 'at', 'by', 'as', 'is', 'it',
    'build', 'create', 'make', 'generate', 'implement', 'write', 'complete', 'premium',
    'modern', 'multi-section', 'landing', 'website', 'webpage', 'page', 'fictional',
    'technology', 'company', 'saas', 'app', 'application', 'site', 'dark', 'aesthetic',
    'responsive', 'include', 'including', 'navbar', 'hero', 'features', 'solutions',
    'dashboard', 'testimonials', 'pricing', 'faq', 'cta', 'footer', 'using', 'html',
    'css', 'js', 'javascript', 'typescript', 'folder', 'directory', 'new', 'task', 'test',
    'project', 'demo', 'sample', 'simple', 'basic', 'web', 'file', 'files', 'frontend',
    'backend', 'local', 'preview', 'server', 'code', 'data', 'database', 'system', 'user',
    'run', 'first', 'second', 'third', 'interface', 'ui', 'ux', 'card', 'cards', 'menu',
    'about', 'contact', 'services', 'service', 'home', 'main', 'header', 'section', 'sections',
    'start building', 'explore platform', 'get started', 'learn more', 'click here',
    'sign up', 'sign in', 'log in', 'login', 'read more', 'buy now', 'contact us',
    'submit', 'subscribe', 'try for free', 'book a demo', 'request demo', 'view all',
    'see more', 'explore more', 'get in touch',
    'generated by nexus ai', 'generated by nexus ai agent', 'nexus ai', 'nexus ai agent',
    'nexus web application', 'nexus'
  ]);

  const candidates: string[] = [];

  // 0. Explicit Project Brand directive in prompt
  const explicitDirectiveMatch = taskGoal.match(/Project Brand \/ Identity:\s*([^\n]+)/i);
  if (explicitDirectiveMatch && explicitDirectiveMatch[1]) {
    const brand = explicitDirectiveMatch[1].trim();
    if (brand && !stopWords.has(brand.toLowerCase())) {
      candidates.push(brand);
      return candidates;
    }
  }

  // 1. Explicit brand declaration patterns (e.g. called NOVARA AI, company called Bean & Brew, for DevForge)
  // Strip folder/directory patterns first so folder names (e.g. 'folder called my-app') are not misidentified as brand names
  const goalWithoutFolder = taskGoal.replace(/(?:in\s+a\s+)?(?:folder|directory|subfolder)\s+(?:called|named)\s+[`"']?[a-zA-Z0-9_\-]+[`"']?/gi, '');

  const namePatterns = [
    /(?:company called|brand called|brand named|for a fictional technology company called|for a fictional ai company called|for an ai company called|for a cafe called|for a company called|for a startup called)\s+[`"']?([a-zA-Z0-9_& -]+?)[`"']?(?:\.|\s+with|\s+that|\s+including|\s+requirements|\s+featuring|\s+and|\s+in\s+a|\s+to|$)/i,
    /(?:called|named)\s+[`"']?([a-zA-Z0-9_& -]+?)[`"']?(?:\.|\s+with|\s+that|\s+including|\s+requirements|\s+featuring|\s+and|\s+in\s+a|\s+to|$)/i,
    /(?:portfolio|landing page|website|web app|app|application)\s+for\s+[`"']?([a-zA-Z0-9_& -]+?)[`"']?(?:\.|\s+with|\s+that|\s+including|\s+requirements|\s+featuring|\s+and|\s+in\s+a|\s+to|$)/i,
    /\bfor\s+[`"']?([A-Z][a-zA-Z0-9_&]+(?:\s+[A-Z][a-zA-Z0-9_&]+)*)[`"']?(?:\.|\s+with|\s+that|\s+including|\s+requirements|\s+featuring|\s+and|\s+in\s+a|\s+to|$)/,
  ];

  for (const pat of namePatterns) {
    const match = goalWithoutFolder.match(pat);
    if (match && match[1]) {
      let val = match[1].trim();
      val = val.replace(/^(?:a|an|the)\s+/i, '').trim();
      if (val.length >= 2 && !stopWords.has(val.toLowerCase()) && !candidates.includes(val)) {
        candidates.push(val);
      }
    }
  }

  // If explicit brand names were identified, return them
  if (candidates.length > 0) {
    return candidates;
  }

  // 2. Match quoted strings e.g. "NEXORA", "Bean & Brew"
  const quotesMatch = taskGoal.match(/"([^"]+)"|'([^']+)'|“([^”]+)”/g);
  if (quotesMatch) {
    for (const q of quotesMatch) {
      const clean = q.replace(/["'“”]/g, '').trim();
      if (clean.length >= 2 && !stopWords.has(clean.toLowerCase()) && !candidates.includes(clean)) {
        candidates.push(clean);
      }
    }
  }

  if (candidates.length > 0) {
    return candidates;
  }

  // 3. Match multi-word capitalized brands or acronyms (e.g., NOVARA AI, NEXORA)
  const multiCapMatch = taskGoal.match(/\b([A-Z][A-Z0-9_-]+(?:\s+[A-Z][A-Z0-9_-]+)+)\b/g);
  if (multiCapMatch) {
    for (const phrase of multiCapMatch) {
      const words = phrase.toLowerCase().split(/\s+/);
      const isAllStopWords = words.every(
        (w) => stopWords.has(w) || /^(html|css|http|url|json|api|cta|faq|todo|tbd|dom|nexus|app|ui|ux|js|ts|task)$/i.test(w)
      );
      if (!isAllStopWords && !candidates.includes(phrase)) {
        candidates.push(phrase);
      }
    }
  }

  if (candidates.length > 0) {
    return candidates;
  }

  // 4. Match single ALL-CAPS acronyms / distinct brand names (e.g., NEXORA, NOVARA)
  const allCapsWords = taskGoal.match(/\b[A-Z0-9_-]{3,}\b/g);
  if (allCapsWords) {
    for (const w of allCapsWords) {
      if (!stopWords.has(w.toLowerCase()) && !candidates.includes(w) && !/^(HTML|CSS|HTTP|URL|JSON|API|CTA|FAQ|TODO|TBD|DOM|NEXUS)$/i.test(w)) {
        candidates.push(w);
      }
    }
  }

  return candidates;
}

/**
 * Extracts requested hero CTA/button or headline terms from parentGoal or unit.
 */
export function extractHeroRequestedTerms(parentGoal: string, unit?: import('./taskDecompositionTypes.js').DecomposedTaskUnit): string[] {
  const terms: string[] = [];

  const unitText = unit ? `${unit.title} ${unit.description} ${unit.expectedOutput} ${unit.verificationCriteria.join(' ')}` : '';
  const combined = `${parentGoal} ${unitText}`;

  // Find quotes near hero / CTA keywords
  const heroMatch = combined.match(/(?:hero|headline|cta\s+buttons?|banner)[^.]*?(?:buttons?|titled|with|saying)?\s*([“"'][^"']+?[”"'](?:\s+and\s+[“"'][^"']+?[”"'])*)/i);
  if (heroMatch && heroMatch[1]) {
    const qMatches = heroMatch[1].match(/["'“”]([^"'“”]+)["'“”]/g);
    if (qMatches) {
      for (const q of qMatches) {
        const clean = q.replace(/["'“”]/g, '').trim();
        if (clean.length >= 2 && !terms.includes(clean)) {
          terms.push(clean);
        }
      }
    }
  }

  // Also check if unit verification criteria explicitly specifies a quoted term
  if (unit) {
    for (const crit of unit.verificationCriteria) {
      const critQuotes = crit.match(/["'“]([^"'“”]+)["'”]/g);
      if (critQuotes) {
        for (const q of critQuotes) {
          const clean = q.replace(/["'“”]/g, '').trim();
          if (clean.length >= 2 && !terms.includes(clean)) {
            terms.push(clean);
          }
        }
      }
    }
  }

  return terms;
}

/**
 * Extracts requested section keys from user task goal using regex boundary matching.
 */
export function extractRequestedSections(taskGoal: string): Array<{ key: string; label: string }> {
  const knownSections = [
    { key: 'navbar', label: 'Navbar / Navigation', regex: /\b(?:navbar|navigation\s+bar|nav\s+bar)\b/i },
    { key: 'hero', label: 'Hero Section', regex: /\b(?:hero|headline)\b/i },
    { key: 'feature', label: 'Features Section', regex: /\b(?:features?|capabilities)\b/i },
    { key: 'solution', label: 'Solutions Section', regex: /\b(?:solutions?)\b/i },
    { key: 'about', label: 'About Section', regex: /\b(?:about\s+us|about\s+section|\babout\b)/i },
    { key: 'dashboard', label: 'Product Dashboard', regex: /\b(?:dashboard|platform\s+mockup|showcase)\b/i },
    { key: 'process', label: 'Process / How It Works', regex: /\b(?:how\s+it\s+works|process|3-step)\b/i },
    { key: 'stat', label: 'Statistics / Metrics', regex: /\b(?:statistics|stats|metrics)\b/i },
    { key: 'testimonial', label: 'Testimonials / Reviews', regex: /\b(?:testimonials?|reviews?)\b/i },
    { key: 'pricing', label: 'Pricing Section', regex: /\b(?:pricing|subscription\s+tier|plans?)\b/i },
    { key: 'faq', label: 'FAQ Accordion', regex: /\b(?:faq|frequently\s+asked|accordion)\b/i },
    { key: 'cta', label: 'Call To Action', regex: /\b(?:cta|call\s+to\s+action)\b/i },
    { key: 'footer', label: 'Footer', regex: /\b(?:footer)\b/i },
    { key: 'menu', label: 'Menu Section', regex: /\b(?:menu\s+grid|food\s+menu|drink\s+menu|restaurant\s+menu|our\s+specialties|\bmenu\b(?!.*?\b(?:toggle|mobile|bar)\b))\b/i },
    { key: 'project', label: 'Projects Section', regex: /\b(?:projects?|featured\s+projects?)\b/i },
    { key: 'skill', label: 'Skills Section', regex: /\b(?:skills?)\b/i },
    { key: 'contact', label: 'Contact Section', regex: /\b(?:contact\s+us|contact\s+section|\bcontact\b)/i },
  ];

  return knownSections.filter((s) => s.regex.test(taskGoal));
}

/**
 * Performs complete, multi-stage content substance and integrity verification
 * on generated HTML content given the original user task goal.
 */
export function verifyHtmlContentSubstance(
  htmlContent: string,
  taskGoal: string
): ContentVerificationResult {
  if (!htmlContent || !htmlContent.trim()) {
    return {
      valid: false,
      errorCategory: 'EMPTY_ARTIFACT',
      reason: 'HTML artifact is empty (0 bytes).',
    };
  }

  const lowerHtml = htmlContent.toLowerCase();
  const lowerGoal = taskGoal.toLowerCase();

  // ── CHECK 1: Non-Empty HTML Body ──────────────────────────────────────────
  const bodyMatch = htmlContent.match(/<body\b[^>]*>([\s\S]*?)<\/body>/i);
  const bodyHtml = bodyMatch ? bodyMatch[1] : htmlContent;
  if (!bodyHtml || !bodyHtml.trim()) {
    return {
      valid: false,
      errorCategory: 'EMPTY_HTML_BODY',
      reason: 'HTML artifact does not contain a non-empty <body> element.',
    };
  }

  // ── CHECK 2: Unresolved Generation Placeholders ───────────────────────────
  const placeholders = detectPlaceholders(htmlContent, taskGoal);
  if (placeholders.hasPlaceholders) {
    return {
      valid: false,
      errorCategory: 'PLACEHOLDER_ARTIFACT_REJECTED',
      reason: `HTML artifact contains unresolved placeholders: ${placeholders.reasons.join('; ')}`,
    };
  }

  // ── CHECK 3: Empty Containers & Comment-Only Skeletons ─────────────────────
  const skeletonCheck = detectSkeletonContainers(htmlContent);
  if (skeletonCheck.isSkeleton) {
    return {
      valid: false,
      errorCategory: 'INCOMPLETE_SKELETON_REJECTED',
      skeletonSections: skeletonCheck.skeletonSectionNames,
      reason: `HTML artifact contains incomplete skeleton containers: ${skeletonCheck.skeletonSectionNames.join(', ')}. ${skeletonCheck.reasons.join(' ')}`,
    };
  }

  // ── CHECK 4: Visible Text Check (Non-Blank Body) ──────────────────────────
  const visibleText = extractVisibleText(bodyHtml);
  const hasVisualElements = /<(?:img|svg|input|button|canvas|form|video|audio|iframe|textarea|select|header|nav|main|aside|section|div|script|table)\b/i.test(bodyHtml);

  if (visibleText.length === 0 && !hasVisualElements) {
    return {
      valid: false,
      errorCategory: 'INSUFFICIENT_PROJECT_CONTENT',
      visibleTextLength: 0,
      reason: 'HTML artifact contains zero visible text. Page renders completely blank.',
    };
  }

  // ── CHECK 5: Brand / Project Identity Evidence ────────────────────────────
  const brandCandidates = extractBrandCandidates(taskGoal);
  let detectedBrand: string | undefined;
  let foundBrand = false;
  const isCalculator = lowerGoal.includes('calculator');

  if (brandCandidates.length > 0) {
    for (const b of brandCandidates) {
      const lowerB = b.toLowerCase();
      const words = lowerB
        .replace(/[-_]/g, ' ')
        .split(/\s+/)
        .filter((w) => w.length >= 3 && !['ai', 'inc', 'corp', 'app', 'ltd', 'co', 'folder', 'directory', 'project'].includes(w));
      const hasWordMatch = words.length > 0 && words.every((w) => lowerHtml.includes(w));
      const hasAnySignificantWord = words.length >= 2 && words.some((w) => lowerHtml.includes(w));
      if (lowerHtml.includes(lowerB) || hasWordMatch || (hasAnySignificantWord && visibleText.length > 50)) {
        foundBrand = true;
        detectedBrand = b;
        break;
      }
    }

    if (!foundBrand && !isCalculator && visibleText.length < 100) {
      return {
        valid: false,
        errorCategory: 'CONTENT_VERIFICATION_FAILED',
        reason: `HTML artifact is missing requested project brand/title terms corresponding to the task goal (${brandCandidates.join(', ')}).`,
      };
    }
  }

  // ── CHECK 6: Request-Aware Section Content Substance ──────────────────────
  const requestedSections = extractRequestedSections(taskGoal);
  if (requestedSections.length >= 3) {
    const missingSections: string[] = [];
    const emptyRequestedSections: string[] = [];

    for (const sec of requestedSections) {
      let inner = '';
      let foundContainer = false;

      const idOrClassRegex = new RegExp(
        `<(section|footer|header|nav|main|article|div)\\b[^>]*?(?:id|class)=["'][^"']*?${sec.key}[^"']*?["'][^>]*>([\\s\\S]*?)<\\/\\1>`,
        'i'
      );
      const match = idOrClassRegex.exec(htmlContent);

      if (match) {
        foundContainer = true;
        inner = match[2] || '';
      } else if (sec.key === 'footer' || sec.key === 'navbar' || sec.key === 'nav') {
        const tag = sec.key === 'footer' ? 'footer' : '(?:header|nav)';
        const tagMatch = new RegExp(`<(${tag})\\b[^>]*>([\\s\\S]*?)<\\/\\1>`, 'i').exec(htmlContent);
        if (tagMatch) {
          foundContainer = true;
          inner = tagMatch[2] || '';
        }
      }

      if (foundContainer) {
        const innerVisible = extractVisibleText(inner);
        const hasVisual = /<(?:img|svg|input|button|canvas|form|ul|ol|table)\b/i.test(inner);
        if (innerVisible.length === 0 && !hasVisual) {
          emptyRequestedSections.push(`${sec.label} (empty/placeholder)`);
        }
      } else if (!lowerHtml.includes(sec.key)) {
        missingSections.push(sec.label);
      }
    }

    if (emptyRequestedSections.length > 0) {
      return {
        valid: false,
        errorCategory: 'INCOMPLETE_SKELETON_REJECTED',
        skeletonSections: emptyRequestedSections,
        reason: `HTML artifact contains empty requested sections without real content: ${emptyRequestedSections.join(', ')}.`,
      };
    }

    if (missingSections.length > Math.floor(requestedSections.length * 0.4)) {
      return {
        valid: false,
        errorCategory: 'INSUFFICIENT_PROJECT_CONTENT',
        missingSections,
        reason: `HTML artifact is missing critical requested sections: ${missingSections.join(', ')}.`,
      };
    }
  }

  // ── CHECK 7: Stale Artifact / Mismatched Project Detection ────────────────
  if (!isCalculator && lowerGoal.includes('landing') && (brandCandidates.length > 0 || lowerGoal.includes('nexora') || lowerGoal.includes('novara'))) {
    if (lowerHtml.includes('class="calculator"') && !foundBrand) {
      return {
        valid: false,
        errorCategory: 'STALE_PROJECT_MISMATCH',
        reason: 'HTML artifact appears to be an unrelated calculator project rather than the requested landing page.',
      };
    }
  }

  if (isCalculator) {
    const hasButtons = lowerHtml.includes('<button') || lowerHtml.includes('class="btn');
    const hasDisplay = lowerHtml.includes('display') || lowerHtml.includes('screen') || lowerHtml.includes('result');
    const hasCalcTerm = lowerHtml.includes('calculator') || lowerHtml.includes('calc');
    if (!hasButtons && !hasDisplay && !hasCalcTerm) {
      return {
        valid: false,
        errorCategory: 'CONTENT_VERIFICATION_FAILED',
        reason: 'Calculator project is missing required calculator content or UI elements (buttons/display/calculator heading).',
      };
    }
  }

  return {
    valid: true,
    visibleTextLength: visibleText.length,
    detectedBrand,
    foundBrand,
  };
}

export interface ChildUnitVerificationOptions {
  unit: import('./taskDecompositionTypes.js').DecomposedTaskUnit;
  parentGoal: string;
}

/**
 * Performs child-task-aware verification for an incremental unit of work.
 * Validates current child requirements and project brand identity without
 * prematurely demanding future child-task sections.
 */
export function verifyChildUnitContentSubstance(
  htmlContent: string,
  options: ChildUnitVerificationOptions
): ContentVerificationResult {
  const { unit, parentGoal } = options;

  if (!htmlContent || !htmlContent.trim()) {
    return {
      valid: false,
      errorCategory: 'EMPTY_ARTIFACT',
      reason: `HTML artifact for unit '${unit.title}' is empty (0 bytes).`,
    };
  }

  const lowerHtml = htmlContent.toLowerCase();
  const lowerUnitTitle = unit.title.toLowerCase();
  const lowerParentGoal = parentGoal.toLowerCase();

  // ── CHECK 1: Non-Empty HTML Body ──────────────────────────────────────────
  const bodyMatch = htmlContent.match(/<body\b[^>]*>([\s\S]*?)<\/body>/i);
  const bodyHtml = bodyMatch ? bodyMatch[1] : htmlContent;
  if (!bodyHtml || !bodyHtml.trim()) {
    return {
      valid: false,
      errorCategory: 'EMPTY_HTML_BODY',
      reason: `HTML artifact for unit '${unit.title}' does not contain a non-empty <body> element.`,
    };
  }

  // ── CHECK 2: Unresolved Generation Placeholders ───────────────────────────
  const placeholders = detectPlaceholders(htmlContent, parentGoal);
  if (placeholders.hasPlaceholders) {
    return {
      valid: false,
      errorCategory: 'PLACEHOLDER_ARTIFACT_REJECTED',
      reason: `HTML artifact contains unresolved placeholders: ${placeholders.reasons.join('; ')}`,
    };
  }

  // ── CHECK 3: Empty Containers & Comment-Only Skeletons ─────────────────────
  const skeletonCheck = detectSkeletonContainers(htmlContent);
  if (skeletonCheck.isSkeleton) {
    return {
      valid: false,
      errorCategory: 'INCOMPLETE_SKELETON_REJECTED',
      skeletonSections: skeletonCheck.skeletonSectionNames,
      reason: `HTML artifact contains incomplete skeleton containers: ${skeletonCheck.skeletonSectionNames.join(', ')}. ${skeletonCheck.reasons.join(' ')}`,
    };
  }

  // ── CHECK 4: Visible Text Check (Non-Blank Body) ──────────────────────────
  const visibleText = extractVisibleText(bodyHtml);
  const hasVisualElements = /<(?:img|svg|input|button|canvas|form|video|audio|iframe)\b/i.test(bodyHtml);

  if (visibleText.length === 0 && !hasVisualElements) {
    return {
      valid: false,
      errorCategory: 'INSUFFICIENT_PROJECT_CONTENT',
      visibleTextLength: 0,
      reason: `HTML artifact for unit '${unit.title}' contains zero visible text. Page renders completely blank.`,
    };
  }

  // ── CHECK 5: Brand / Project Identity Evidence ────────────────────────────
  const brandCandidates = extractBrandCandidates(parentGoal);
  let detectedBrand: string | undefined;
  let foundBrand = false;
  const isCalculator = lowerParentGoal.includes('calculator') || lowerUnitTitle.includes('calculator');

  if (brandCandidates.length > 0) {
    for (const b of brandCandidates) {
      const lowerB = b.toLowerCase();
      const words = lowerB.split(/\s+/).filter((w) => w.length >= 3 && !['ai', 'inc', 'corp', 'app', 'ltd', 'co'].includes(w));
      const hasWordMatch = words.length > 0 && words.every((w) => lowerHtml.includes(w));
      if (lowerHtml.includes(lowerB) || hasWordMatch) {
        foundBrand = true;
        detectedBrand = b;
        break;
      }
    }

    if (!foundBrand && !isCalculator) {
      return {
        valid: false,
        errorCategory: 'CONTENT_VERIFICATION_FAILED',
        reason: `HTML artifact is missing requested project brand/title terms corresponding to the task goal (${brandCandidates.join(', ')}).`,
      };
    }
  }

  // ── CHECK 6: Stale Artifact / Mismatched Project Detection ────────────────
  if (!isCalculator && lowerParentGoal.includes('landing') && (brandCandidates.length > 0 || lowerParentGoal.includes('nexora') || lowerParentGoal.includes('novara'))) {
    if (lowerHtml.includes('class="calculator"') && !foundBrand) {
      return {
        valid: false,
        errorCategory: 'STALE_PROJECT_MISMATCH',
        reason: 'HTML artifact appears to be an unrelated calculator project rather than the requested landing page.',
      };
    }
  }

  if (isCalculator && (unit.id.includes('foundation') || unit.id.includes('integration') || unit.category === 'foundation')) {
    const hasButtons = lowerHtml.includes('<button') || lowerHtml.includes('class="btn');
    const hasDisplay = lowerHtml.includes('display') || lowerHtml.includes('screen') || lowerHtml.includes('result');
    const hasCalcTerm = lowerHtml.includes('calculator') || lowerHtml.includes('calc');
    if (!hasButtons && !hasDisplay && !hasCalcTerm) {
      return {
        valid: false,
        errorCategory: 'CONTENT_VERIFICATION_FAILED',
        reason: 'Calculator project is missing required calculator content or UI elements (buttons/display/calculator heading).',
      };
    }
  }

  // ── CHECK 7: Child-Unit Focused Requirement Verification ───────────────────
  // A. Foundation Unit:
  if (unit.id.includes('foundation') || unit.category === 'foundation') {
    const hasDoctypeOrHtml = /<!doctype\s+html|<html\b/i.test(htmlContent);
    const hasHead = /<head\b/i.test(htmlContent);
    const hasTitle = /<title\b/i.test(htmlContent);
    const hasBody = /<body\b/i.test(htmlContent);
    if (!hasDoctypeOrHtml || !hasHead || !hasTitle || !hasBody) {
      return {
        valid: false,
        errorCategory: 'INVALID_FOUNDATION_STRUCTURE',
        reason: `HTML artifact for foundation unit '${unit.title}' is missing standard HTML5 structure elements (DOCTYPE, head, title, body).`,
      };
    }
    return {
      valid: true,
      visibleTextLength: visibleText.length,
      detectedBrand,
      foundBrand,
    };
  }

  // B. Navbar / Header Unit:
  if (unit.id.includes('navbar') || lowerUnitTitle.includes('navbar') || lowerUnitTitle.includes('navigation header')) {
    const hasNav = /<(?:header|nav)\b/i.test(htmlContent) || /(?:id|class)=["'][^"']*(?:navbar|nav-container|site-header|navigation)[^"']*["']/i.test(htmlContent);
    if (!hasNav) {
      return {
        valid: false,
        errorCategory: 'MISSING_NAVBAR_SECTION',
        reason: `HTML artifact is missing the navigation header element (<header>, <nav>, or navbar container) required by unit '${unit.title}'.`,
      };
    }
  }

  // C. Hero Unit:
  if (unit.id.includes('hero') || lowerUnitTitle.includes('hero')) {
    const hasHero = /<section\b[^>]*?(?:id|class)=["'][^"']*?hero[^"']*?["']/i.test(htmlContent) || /<h1\b/i.test(htmlContent);
    if (!hasHero) {
      return {
        valid: false,
        errorCategory: 'MISSING_HERO_SECTION',
        reason: `HTML artifact is missing the hero section (<section class="hero"> or <h1> heading) required by unit '${unit.title}'.`,
      };
    }

    const heroTermsToCheck = extractHeroRequestedTerms(parentGoal, unit);
    const missingHeroTerms: string[] = [];
    for (const term of heroTermsToCheck) {
      if (!lowerHtml.includes(term.toLowerCase())) {
        missingHeroTerms.push(term);
      }
    }
    if (missingHeroTerms.length > 0) {
      return {
        valid: false,
        errorCategory: 'MISSING_HERO_CONTENT',
        reason: `Hero section is missing requested hero content/CTA terms: ${missingHeroTerms.join(', ')}.`,
      };
    }
  }

  // D. Features Unit:
  if (unit.id.includes('features') || lowerUnitTitle.includes('feature')) {
    const hasFeatures = /<(?:section|div)\b[^>]*?(?:id|class)=["'][^"']*?feature[^"']*?["']/i.test(htmlContent) || lowerHtml.includes('feature');
    if (!hasFeatures) {
      return {
        valid: false,
        errorCategory: 'MISSING_FEATURES_SECTION',
        reason: `HTML artifact is missing the features section required by unit '${unit.title}'.`,
      };
    }
  }

  // E. Solutions / Menu Unit:
  if (unit.id.includes('solutions') || unit.id.includes('menu') || lowerUnitTitle.includes('solution') || lowerUnitTitle.includes('menu')) {
    const key = unit.id.includes('menu') ? 'menu' : 'solution';
    const hasSection = new RegExp(`<(?:section|div)\\b[^>]*?(?:id|class)=["'][^"']*?${key}[^"']*?["']`, 'i').test(htmlContent) || lowerHtml.includes(key);
    if (!hasSection) {
      return {
        valid: false,
        errorCategory: `MISSING_${key.toUpperCase()}_SECTION`,
        reason: `HTML artifact is missing the ${key} section required by unit '${unit.title}'.`,
      };
    }
  }

  // F. Dashboard Unit:
  if (unit.id.includes('dashboard') || lowerUnitTitle.includes('dashboard')) {
    const hasDashboard = /<(?:section|div)\b[^>]*?(?:id|class)=["'][^"']*?dashboard[^"']*?["']/i.test(htmlContent) || lowerHtml.includes('dashboard') || lowerHtml.includes('metric');
    if (!hasDashboard) {
      return {
        valid: false,
        errorCategory: 'MISSING_DASHBOARD_SECTION',
        reason: `HTML artifact is missing the product dashboard section required by unit '${unit.title}'.`,
      };
    }
  }

  // G. Testimonials Unit:
  if (unit.id.includes('testimonials') || lowerUnitTitle.includes('testimonial')) {
    const hasTestimonials = /<(?:section|div)\b[^>]*?(?:id|class)=["'][^"']*?testimonial[^"']*?["']/i.test(htmlContent) || lowerHtml.includes('testimonial') || lowerHtml.includes('review');
    if (!hasTestimonials) {
      return {
        valid: false,
        errorCategory: 'MISSING_TESTIMONIALS_SECTION',
        reason: `HTML artifact is missing the testimonials section required by unit '${unit.title}'.`,
      };
    }
  }

  // H. Pricing Unit:
  if (unit.id.includes('pricing') || lowerUnitTitle.includes('pricing')) {
    const hasPricing = /<(?:section|div)\b[^>]*?(?:id|class)=["'][^"']*?pricing[^"']*?["']/i.test(htmlContent) || lowerHtml.includes('pricing') || lowerHtml.includes('plan');
    if (!hasPricing) {
      return {
        valid: false,
        errorCategory: 'MISSING_PRICING_SECTION',
        reason: `HTML artifact is missing the pricing section required by unit '${unit.title}'.`,
      };
    }
    const hasPricingContent = /\$\d+|\/mo|\/month|tier|starter|pro|enterprise|free/i.test(htmlContent);
    if (!hasPricingContent) {
      return {
        valid: false,
        errorCategory: 'INSUFFICIENT_PRICING_CONTENT',
        reason: `Pricing section is missing pricing tiers, amounts, or plan details.`,
      };
    }
  }

  // I. FAQ Unit:
  if (unit.id.includes('faq') || lowerUnitTitle.includes('faq') || lowerUnitTitle.includes('frequently asked')) {
    const hasFaq = /<(?:section|div)\b[^>]*?(?:id|class)=["'][^"']*?faq[^"']*?["']/i.test(htmlContent) || lowerHtml.includes('faq') || lowerHtml.includes('accordion') || lowerHtml.includes('frequently asked');
    if (!hasFaq) {
      return {
        valid: false,
        errorCategory: 'MISSING_FAQ_SECTION',
        reason: `HTML artifact is missing the FAQ section required by unit '${unit.title}'.`,
      };
    }
    const hasQuestion = /\?|question|accordion/i.test(htmlContent);
    if (!hasQuestion) {
      return {
        valid: false,
        errorCategory: 'INSUFFICIENT_FAQ_CONTENT',
        reason: `FAQ section is missing question and answer content.`,
      };
    }
  }

  // J. CTA / Footer Unit:
  if (unit.id.includes('cta') || unit.id.includes('footer') || lowerUnitTitle.includes('footer')) {
    const hasFooter = /<footer\b/i.test(htmlContent) || /(?:id|class)=["'][^"']*?footer[^"']*?["']/i.test(htmlContent);
    if (!hasFooter) {
      return {
        valid: false,
        errorCategory: 'MISSING_FOOTER_SECTION',
        reason: `HTML artifact is missing the footer element required by unit '${unit.title}'.`,
      };
    }
  }

  return {
    valid: true,
    visibleTextLength: visibleText.length,
    detectedBrand,
    foundBrand,
  };
}

