/**
 * NEXUS AI — Child-Task-Aware Verification & Substance Regression Tests
 *
 * Validates requirements:
 * TEST A: User requests NOVARA AI -> Verifier can require NOVARA AI.
 * TEST B: User does NOT request "Generated by NEXUS AI" -> Verifier must NOT require "Generated by NEXUS AI".
 * TEST C: Unit 1 foundation does NOT fail because pricing/FAQ/testimonials are not present yet.
 * TEST D: Hero child DOES require its hero-specific requested content.
 * TEST E: Pricing child DOES require pricing content.
 * TEST F: FAQ child DOES require FAQ content.
 * TEST G: Placeholder HTML still fails.
 * TEST H: Empty HTML still fails.
 * TEST I: Unrelated old project content still fails.
 * TEST J: Final integration verifies the complete parent project against the original request.
 */

import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import {
  extractBrandCandidates,
  verifyHtmlContentSubstance,
  verifyChildUnitContentSubstance,
} from '../orchestration/placeholderDetector.js';
import { TaskDecompositionService } from '../orchestration/taskDecompositionService.js';
import type { DecomposedTaskUnit } from '../orchestration/taskDecompositionTypes.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

describe('Child-Task-Aware Content Verification Suite (Tests A-J)', () => {
  const parentGoal =
    'Build a complete premium modern landing page for a fictional AI company called NOVARA AI with hero section with "Start Building" and "Explore Platform" buttons, features, pricing, and FAQ';

  const unit1Foundation: DecomposedTaskUnit = {
    id: 'unit-1-foundation',
    title: 'Project Foundation & Base Layout',
    description: 'Scaffold complete, semantic HTML5 structure for NOVARA AI including meta tags and base CSS variables.',
    category: 'foundation',
    dependencies: [],
    targetFiles: ['index.html', 'styles.css'],
    expectedOutput: "Valid HTML5 document with title containing 'NOVARA AI', linked stylesheets, and CSS design tokens.",
    verificationCriteria: ['index.html has DOCTYPE, head, title, and body', 'styles.css has root color tokens and reset rules'],
  };

  const unit3Hero: DecomposedTaskUnit = {
    id: 'unit-3-hero',
    title: 'Hero Section & Value Proposition',
    description: 'Create high-impact Hero banner with headline, sub-headline, primary CTA "Start Building" and secondary CTA "Explore Platform" for NOVARA AI.',
    category: 'component',
    dependencies: ['unit-1-foundation'],
    targetFiles: ['index.html', 'styles.css'],
    expectedOutput: 'Rich hero section with bold typography, value proposition paragraph, "Start Building" and "Explore Platform" buttons.',
    verificationCriteria: ['hero section exists with h1 heading', 'CTA buttons "Start Building" and "Explore Platform" present with real text', 'No placeholder comments'],
  };

  const unit8Pricing: DecomposedTaskUnit = {
    id: 'unit-8-pricing',
    title: 'Tiered Pricing & Plans',
    description: 'Implement tiered pricing table (e.g. Starter, Professional, Enterprise) with feature comparison lists for NOVARA AI.',
    category: 'component',
    dependencies: ['unit-3-hero'],
    targetFiles: ['index.html', 'styles.css'],
    expectedOutput: 'Pricing section with 3 tier cards, feature checklists, prices ($/mo), and selection buttons.',
    verificationCriteria: ['pricing section exists with 3 pricing cards', 'Pricing numbers, features, and buttons present'],
  };

  const unit9Faq: DecomposedTaskUnit = {
    id: 'unit-9-faq',
    title: 'Frequently Asked Questions (FAQ)',
    description: 'Build FAQ accordion section with 4 to 6 common questions and detailed answers regarding NOVARA AI.',
    category: 'component',
    dependencies: ['unit-8-pricing'],
    targetFiles: ['index.html', 'styles.css', 'scripts.js'],
    expectedOutput: 'FAQ accordion with 4+ questions and expandable answer panels with JavaScript toggling.',
    verificationCriteria: ['faq section exists with questions and answers', 'No skeleton or placeholder questions'],
  };

  // ── TEST A: User requests NOVARA AI -> Verifier can require NOVARA AI ─────
  it('TEST A: User requests NOVARA AI -> Verifier requires NOVARA AI brand identity', () => {
    const candidates = extractBrandCandidates(parentGoal);
    expect(candidates).toContain('NOVARA AI');

    const htmlWithoutBrand = `<!DOCTYPE html>
<html>
<head><title>Generic SaaS Platform</title><link rel="stylesheet" href="styles.css"></head>
<body><header><h1>Autonomous Intelligence</h1></header></body>
</html>`;

    const res = verifyHtmlContentSubstance(htmlWithoutBrand, parentGoal);
    expect(res.valid).toBe(false);
    expect(res.errorCategory).toBe('CONTENT_VERIFICATION_FAILED');
    expect(res.reason).toContain('NOVARA AI');
  });

  // ── TEST B: User does NOT request "Generated by NEXUS AI" -> Must NOT require it
  it('TEST B: User does NOT request "Generated by NEXUS AI" -> Verifier must NOT require "Generated by NEXUS AI"', () => {
    const candidates = extractBrandCandidates(parentGoal);
    expect(candidates).not.toContain('Generated by NEXUS AI');
    expect(candidates).not.toContain('NEXUS AI');
    expect(candidates).not.toContain('Start Building');
    expect(candidates).not.toContain('Explore Platform');

    const cleanFoundationHtml = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>NOVARA AI — Enterprise Intelligence</title><link rel="stylesheet" href="styles.css"></head>
<body><div id="app"><header class="header">NOVARA AI</header></div></body>
</html>`;

    const res = verifyChildUnitContentSubstance(cleanFoundationHtml, {
      unit: unit1Foundation,
      parentGoal,
    });
    expect(res.valid).toBe(true);
    expect(res.reason).toBeUndefined();
  });

  // ── TEST C: Unit 1 foundation does NOT fail because pricing/FAQ/testimonials are not present yet
  it('TEST C: Unit 1 foundation passes without requiring future sections (pricing, FAQ, testimonials, CTA)', () => {
    const unit1Html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NOVARA AI — Next Generation Autonomous AI</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div id="app" class="app-root">
    <div class="layout-container">
      <header class="header"><div class="logo">NOVARA AI</div></header>
      <main id="main-content"><div class="intro">Welcome to NOVARA AI</div></main>
    </div>
  </div>
</body>
</html>`;

    // Must NOT fail on missing pricing, FAQ, testimonials, dashboard
    const res = verifyChildUnitContentSubstance(unit1Html, {
      unit: unit1Foundation,
      parentGoal,
    });

    expect(res.valid).toBe(true);
    expect(res.foundBrand).toBe(true);
  });

  // ── TEST D: Hero child DOES require its hero-specific requested content ───
  it('TEST D: Hero child requires hero section and hero-specific requested CTA terms', () => {
    // Missing hero section -> fails
    const htmlNoHero = `<!DOCTYPE html><html><head><title>NOVARA AI</title></head><body><header>NOVARA AI</header></body></html>`;
    const resNoHero = verifyChildUnitContentSubstance(htmlNoHero, { unit: unit3Hero, parentGoal });
    expect(resNoHero.valid).toBe(false);
    expect(resNoHero.errorCategory).toBe('MISSING_HERO_SECTION');

    // Hero section missing requested CTA button terms ("Start Building", "Explore Platform") -> fails
    const htmlHeroWithoutButtons = `<!DOCTYPE html>
<html>
<head><title>NOVARA AI</title></head>
<body>
  <section class="hero">
    <h1>NOVARA AI — Autonomous Cloud Computing</h1>
    <p>Supercharge developer workflows with our agent runtime.</p>
    <button>Get Started</button>
  </section>
</body>
</html>`;
    const resMissingButtons = verifyChildUnitContentSubstance(htmlHeroWithoutButtons, { unit: unit3Hero, parentGoal });
    expect(resMissingButtons.valid).toBe(false);
    expect(resMissingButtons.errorCategory).toBe('MISSING_HERO_CONTENT');
    expect(resMissingButtons.reason).toContain('Start Building');

    // Complete hero section with requested CTA button terms -> passes
    const htmlHeroComplete = `<!DOCTYPE html>
<html>
<head><title>NOVARA AI</title></head>
<body>
  <section class="hero">
    <h1>NOVARA AI — Autonomous Cloud Computing</h1>
    <p>Supercharge developer workflows with our agent runtime.</p>
    <div class="hero-actions">
      <a href="#build" class="btn btn-primary">Start Building</a>
      <a href="#platform" class="btn btn-secondary">Explore Platform</a>
    </div>
  </section>
</body>
</html>`;
    const resCompleteHero = verifyChildUnitContentSubstance(htmlHeroComplete, { unit: unit3Hero, parentGoal });
    expect(resCompleteHero.valid).toBe(true);
  });

  // ── TEST E: Pricing child DOES require pricing content ────────────────────
  it('TEST E: Pricing child requires pricing section and tiered pricing content', () => {
    const htmlNoPricing = `<!DOCTYPE html><html><head><title>NOVARA AI</title></head><body><section class="hero"><h1>NOVARA AI</h1></section></body></html>`;
    const resNoPricing = verifyChildUnitContentSubstance(htmlNoPricing, { unit: unit8Pricing, parentGoal });
    expect(resNoPricing.valid).toBe(false);
    expect(resNoPricing.errorCategory).toBe('MISSING_PRICING_SECTION');

    const htmlValidPricing = `<!DOCTYPE html>
<html>
<head><title>NOVARA AI</title></head>
<body>
  <section id="pricing" class="pricing">
    <h2>Transparent Pricing</h2>
    <div class="pricing-grid">
      <div class="tier-card"><h3>Starter</h3><p class="price">$29/mo</p></div>
      <div class="tier-card featured"><h3>Professional</h3><p class="price">$79/mo</p></div>
      <div class="tier-card"><h3>Enterprise</h3><p class="price">$199/mo</p></div>
    </div>
  </section>
</body>
</html>`;
    const resValidPricing = verifyChildUnitContentSubstance(htmlValidPricing, { unit: unit8Pricing, parentGoal });
    expect(resValidPricing.valid).toBe(true);
  });

  // ── TEST F: FAQ child DOES require FAQ content ────────────────────────────
  it('TEST F: FAQ child requires FAQ section with question and answer content', () => {
    const htmlNoFaq = `<!DOCTYPE html><html><head><title>NOVARA AI</title></head><body><section class="pricing"><h2>$29/mo</h2></section></body></html>`;
    const resNoFaq = verifyChildUnitContentSubstance(htmlNoFaq, { unit: unit9Faq, parentGoal });
    expect(resNoFaq.valid).toBe(false);
    expect(resNoFaq.errorCategory).toBe('MISSING_FAQ_SECTION');

    const htmlValidFaq = `<!DOCTYPE html>
<html>
<head><title>NOVARA AI</title></head>
<body>
  <section id="faq" class="faq-section">
    <h2>Frequently Asked Questions</h2>
    <div class="faq-accordion">
      <div class="faq-item"><h3>What is NOVARA AI?</h3><p>An enterprise-grade autonomous agent platform.</p></div>
      <div class="faq-item"><h3>How do I deploy?</h3><p>Use our one-click CLI or cloud console.</p></div>
    </div>
  </section>
</body>
</html>`;
    const resValidFaq = verifyChildUnitContentSubstance(htmlValidFaq, { unit: unit9Faq, parentGoal });
    expect(resValidFaq.valid).toBe(true);
  });

  // ── TEST G: Placeholder HTML still fails ──────────────────────────────────
  it('TEST G: Placeholder HTML still fails verification', () => {
    const placeholderHtml = `<!DOCTYPE html>
<html>
<head><title>NOVARA AI</title></head>
<body>
  <header>NOVARA AI</header>
  <section class="hero">
    <!-- Hero Content -->
  </section>
  <section class="features">
    <!-- Features Content -->
  </section>
</body>
</html>`;

    const res = verifyChildUnitContentSubstance(placeholderHtml, { unit: unit1Foundation, parentGoal });
    expect(res.valid).toBe(false);
    expect(res.errorCategory).toMatch(/PLACEHOLDER_ARTIFACT_REJECTED|INCOMPLETE_SKELETON_REJECTED/);
  });

  // ── TEST H: Empty HTML still fails ────────────────────────────────────────
  it('TEST H: Empty HTML still fails verification', () => {
    const emptyHtml = ``;
    const resEmpty = verifyChildUnitContentSubstance(emptyHtml, { unit: unit1Foundation, parentGoal });
    expect(resEmpty.valid).toBe(false);
    expect(resEmpty.errorCategory).toBe('EMPTY_ARTIFACT');

    const emptyBodyHtml = `<!DOCTYPE html><html><head><title>NOVARA AI</title></head><body></body></html>`;
    const resEmptyBody = verifyChildUnitContentSubstance(emptyBodyHtml, { unit: unit1Foundation, parentGoal });
    expect(resEmptyBody.valid).toBe(false);
    expect(resEmptyBody.errorCategory).toBe('EMPTY_HTML_BODY');
  });

  // ── TEST I: Unrelated old project content still fails ─────────────────────
  it('TEST I: Unrelated old project content still fails verification', () => {
    const staleCalcHtml = `<!DOCTYPE html>
<html>
<head><title>Online Calculator</title></head>
<body>
  <div class="calculator">
    <div class="display">0</div>
    <div class="buttons">
      <button class="btn">1</button>
      <button class="btn">+</button>
    </div>
  </div>
</body>
</html>`;

    const res = verifyChildUnitContentSubstance(staleCalcHtml, { unit: unit1Foundation, parentGoal });
    expect(res.valid).toBe(false);
    expect(res.errorCategory).toMatch(/CONTENT_VERIFICATION_FAILED|STALE_PROJECT_MISMATCH/);
  });

  // ── TEST J: Final integration verifies the complete parent project against the original request ──
  it('TEST J: Final integration verifies complete parent project with all requested sections', () => {
    const completeProjectHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>NOVARA AI — Next Gen AI Platform</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header class="navbar"><div class="logo">NOVARA AI</div><nav><a href="#hero">Home</a><a href="#features">Features</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></nav></header>
  <main>
    <section id="hero" class="hero">
      <h1>NOVARA AI: Next Gen Intelligence</h1>
      <p>Transforming enterprise software development with agent orchestration.</p>
      <a href="#start" class="btn">Start Building</a>
      <a href="#explore" class="btn">Explore Platform</a>
    </section>
    <section id="features" class="features">
      <h2>Core Features</h2>
      <p>Discover neural task execution, zero-latency inference, and sandbox security.</p>
    </section>
    <section id="pricing" class="pricing">
      <h2>Simple Pricing</h2>
      <p>Flexible tiers for startups and global enterprises starting at $49/mo.</p>
    </section>
    <section id="faq" class="faq">
      <h2>Frequently Asked Questions</h2>
      <div class="faq-item"><h3>How does NOVARA work?</h3><p>Through state-of-the-art multi-agent execution.</p></div>
    </section>
  </main>
  <footer id="footer"><p>&copy; 2026 NOVARA AI Inc. All rights reserved.</p></footer>
</body>
</html>`;

    const finalRes = verifyHtmlContentSubstance(completeProjectHtml, parentGoal);
    expect(finalRes.valid).toBe(true);
    expect(finalRes.foundBrand).toBe(true);
    expect(finalRes.detectedBrand).toBe('NOVARA AI');

  });
});

describe('Generic Project Identity Propagation & Unit 1 Generation (Tests 1-7)', () => {
  const decompositionService = new TaskDecompositionService();

  // ── TEST 1: "Build a landing page for NOVARA AI" -> Unit 1 context contains NOVARA AI ──
  it('TEST 1: "Build a landing page for NOVARA AI" -> Decomposed units and context contain NOVARA AI', async () => {
    const goal = 'Build a complete premium modern landing page for a fictional AI company called NOVARA AI';
    const plan = await decompositionService.decompose({ taskGoal: goal });

    expect(plan.isDecomposed).toBe(true);
    expect(plan.units.length).toBeGreaterThanOrEqual(3);
    const unit1 = plan.units[0];
    expect(unit1.title).toContain('Foundation');
    expect(unit1.description).toContain('NOVARA AI');
    expect(unit1.expectedOutput).toContain('NOVARA AI');
  });

  // ── TEST 2: "Build a landing page for Bean & Brew" -> Unit 1 context contains Bean & Brew ──
  it('TEST 2: "Build a landing page for Bean & Brew" -> Decomposed units and context contain Bean & Brew', async () => {
    const goal = 'Build a complete modern landing page for a cafe called Bean & Brew';
    const plan = await decompositionService.decompose({ taskGoal: goal });

    expect(plan.isDecomposed).toBe(true);
    const unit1 = plan.units[0];
    expect(unit1.description).toContain('Bean & Brew');
    expect(unit1.expectedOutput).toContain('Bean & Brew');
  });

  // ── TEST 3: "Build a developer portfolio for DevForge" -> Unit 1 context contains DevForge ──
  it('TEST 3: "Build a developer portfolio for DevForge" -> Decomposed units and context contain DevForge', async () => {
    const goal = 'Build a modern developer portfolio for DevForge with featured projects, skills, and contact';
    const plan = await decompositionService.decompose({ taskGoal: goal });

    expect(plan.isDecomposed).toBe(true);
    const unit1 = plan.units[0];
    expect(unit1.description).toContain('DevForge');
    expect(unit1.expectedOutput).toContain('DevForge');
  });

  // ── TEST 4: No hardcoded project names exist in orchestration logic ─────────
  it('TEST 4: No hardcoded project names exist in orchestration logic', () => {
    const orchSource = fs.readFileSync(path.resolve(__dirname, '../orchestration/projectOrchestrator.ts'), 'utf8');
    const decompSource = fs.readFileSync(path.resolve(__dirname, '../orchestration/taskDecompositionService.ts'), 'utf8');

    // Orchestrator logic must NOT contain hardcoded project name matches like `=== "NOVARA AI"` or `if (brand === "NOVARA AI")`
    expect(orchSource).not.toMatch(/=== ['"]NOVARA AI['"]/i);
    expect(orchSource).not.toMatch(/=== ['"]Bean & Brew['"]/i);
    expect(decompSource).not.toMatch(/=== ['"]NOVARA AI['"]/i);
    expect(decompSource).not.toMatch(/=== ['"]Bean & Brew['"]/i);
  });

  // ── TEST 5: Unit 1 generated foundation includes the extracted project identity ──
  it('TEST 5: Unit 1 generated foundation includes the extracted project identity', async () => {
    const { EmbeddedInferenceProvider } = await import('../intelligence/providers/embeddedInferenceProvider.js');
    const provider = new EmbeddedInferenceProvider();
    await provider.initialize();

    // Generate for NOVARA AI child task
    const childPromptNovara = [
      'TASK GOAL:',
      'Project Brand / Identity: NOVARA AI',
      'Overall Project: Build a complete premium modern landing page for a fictional AI company called NOVARA AI',
      'Current Unit (FOUNDATION): Project Foundation & Base Layout',
      'Unit Instructions: Scaffold complete HTML5 structure for NOVARA AI',
      'Target Files: index.html, styles.css',
      'Expected Output: Valid HTML5 document with title containing NOVARA AI',
      'Verification Criteria: index.html has DOCTYPE, head, title, and body',
      "Brand Directive: You must explicitly incorporate the project brand 'NOVARA AI' into the code/markup.",
    ].join('\n');

    const resNovara = await provider.generate({
      prompt: childPromptNovara,
      system: 'You are a deterministic task planner for the NEXUS AI Agent Runtime. REQUIRED OUTPUT FORMAT: JSON',
    });

    const parsedNovara = JSON.parse(resNovara.response) as { steps: Array<{ params: { path: string; content: string } }> };
    const htmlStepNovara = parsedNovara.steps.find((s) => s.params.path.endsWith('.html'));
    expect(htmlStepNovara).toBeDefined();
    expect(htmlStepNovara?.params.content).toContain('NOVARA AI');
    expect(htmlStepNovara?.params.content).toMatch(/<title>[^<]*NOVARA AI/i);

    // Generate for Bean & Brew child task
    const childPromptBean = [
      'TASK GOAL:',
      'Project Brand / Identity: Bean & Brew',
      'Overall Project: Build a modern landing page for Bean & Brew',
      'Current Unit (FOUNDATION): Project Foundation & Base Layout',
      'Unit Instructions: Scaffold complete HTML5 structure for Bean & Brew',
      'Target Files: index.html, styles.css',
      'Expected Output: Valid HTML5 document with title containing Bean & Brew',
      'Verification Criteria: index.html has DOCTYPE, head, title, and body',
    ].join('\n');

    const resBean = await provider.generate({
      prompt: childPromptBean,
      system: 'You are a deterministic task planner for the NEXUS AI Agent Runtime. REQUIRED OUTPUT FORMAT: JSON',
    });

    const parsedBean = JSON.parse(resBean.response) as { steps: Array<{ params: { path: string; content: string } }> };
    const htmlStepBean = parsedBean.steps.find((s) => s.params.path.endsWith('.html'));
    expect(htmlStepBean).toBeDefined();
    expect(htmlStepBean?.params.content).toContain('Bean & Brew');
    expect(htmlStepBean?.params.content).toMatch(/<title>[^<]*Bean & Brew/i);
  });

  // ── TEST 6: Child verification still rejects missing project identity ─────
  it('TEST 6: Child verification still rejects missing project identity', () => {
    const parentGoal = 'Build a complete modern landing page for NOVARA AI';
    const unit1Foundation: DecomposedTaskUnit = {
      id: 'unit-1-foundation',
      title: 'Project Foundation & Base Layout',
      description: 'Scaffold HTML5 foundation for NOVARA AI',
      category: 'foundation',
      dependencies: [],
      targetFiles: ['index.html', 'styles.css'],
      expectedOutput: 'HTML5 foundation for NOVARA AI',
      verificationCriteria: ['title contains NOVARA AI'],
    };

    const wrongBrandHtml = `<!DOCTYPE html>
<html>
<head><title>Some Random Startup</title><link rel="stylesheet" href="styles.css"></head>
<body><header>Welcome</header><main><p>Content</p></main></body>
</html>`;

    const res = verifyChildUnitContentSubstance(wrongBrandHtml, {
      unit: unit1Foundation,
      parentGoal,
    });

    expect(res.valid).toBe(false);
    expect(res.reason).toContain('NOVARA AI');
  });

  // ── TEST 7: Child verification still rejects placeholders ─────────────────
  it('TEST 7: Child verification still rejects placeholders', () => {
    const parentGoal = 'Build a complete modern landing page for NOVARA AI';
    const unit1Foundation: DecomposedTaskUnit = {
      id: 'unit-1-foundation',
      title: 'Project Foundation & Base Layout',
      description: 'Scaffold HTML5 foundation for NOVARA AI',
      category: 'foundation',
      dependencies: [],
      targetFiles: ['index.html', 'styles.css'],
      expectedOutput: 'HTML5 foundation for NOVARA AI',
      verificationCriteria: ['title contains NOVARA AI'],
    };

    const placeholderHtml = `<!DOCTYPE html>
<html>
<head><title>NOVARA AI</title><link rel="stylesheet" href="styles.css"></head>
<body>
  <!-- TODO: implement foundation layout here -->
  <header>NOVARA AI</header>
  <main>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
  </main>
</body>
</html>`;

    const res = verifyChildUnitContentSubstance(placeholderHtml, {
      unit: unit1Foundation,
      parentGoal,
    });

    expect(res.valid).toBe(false);
    expect(res.errorCategory).toMatch(/PLACEHOLDER_ARTIFACT_REJECTED/);
  });
});
