/**
 * NEXUS AI — P7-H: Local Web Project Preview HTTP Server
 *
 * Provides a lightweight, secure local static HTTP file server for previewing
 * web applications generated by NEXUS AI agent tasks.
 *
 * SECURITY INVARIANTS:
 *  - Binds ONLY to loopback IPv4 address 127.0.0.1 (never 0.0.0.0).
 *  - Dynamic port allocation (no hardcoded ports).
 *  - Strict path traversal prevention: all requested paths are canonicalized
 *    and verified to be strictly within the selected project directory.
 *  - Serves read-only content without modifying project files.
 */

import * as http from 'http';
import * as fs from 'fs';
import * as path from 'path';
import * as net from 'net';
import type { PreviewServerInfo } from './previewTypes.js';
import { Logger } from '../common/logger.js';

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.htm': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.webp': 'image/webp',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.otf': 'font/otf',
  '.txt': 'text/plain; charset=utf-8',
};

function isSubpathOrEqual(parentDir: string, childPath: string): boolean {
  const isWin = process.platform === 'win32';
  const p = isWin ? parentDir.toLowerCase() : parentDir;
  const c = isWin ? childPath.toLowerCase() : childPath;
  return c === p || c.startsWith(p + (isWin ? '\\' : '/')) || c.startsWith(p + path.sep);
}

export class PreviewServer {
  private server: http.Server | null = null;
  private logger: Logger;
  private currentInfo: PreviewServerInfo | null = null;
  private activeSockets = new Set<net.Socket>();

  constructor(logLevel: import('../common/logger.js').LogLevel = 'info') {
    this.logger = new Logger('PreviewServer', logLevel);
  }

  /**
   * Find an available TCP port bound to 127.0.0.1.
   */
  private static async findFreePort(preferredPort?: number): Promise<number> {
    if (preferredPort && preferredPort > 0) {
      const isFree = await new Promise<boolean>((resolve) => {
        const s = net.createServer();
        s.once('error', () => resolve(false));
        s.once('listening', () => {
          s.close(() => resolve(true));
        });
        s.listen(preferredPort, '127.0.0.1');
      });
      if (isFree) return preferredPort;
    }

    return new Promise<number>((resolve, reject) => {
      const s = net.createServer();
      s.once('error', (err) => reject(err));
      s.once('listening', () => {
        const addr = s.address();
        const port = typeof addr === 'object' && addr ? addr.port : 0;
        s.close(() => resolve(port));
      });
      s.listen(0, '127.0.0.1');
    });
  }

  /**
   * Start serving files from the given project directory.
   */
  async start(
    projectDir: string,
    entryFile = 'index.html',
    preferredPort?: number
  ): Promise<PreviewServerInfo> {
    if (this.server) {
      await this.stop();
    }

    // Canonicalize project directory
    const resolvedDir = path.resolve(projectDir);
    if (!fs.existsSync(resolvedDir) || !fs.statSync(resolvedDir).isDirectory()) {
      throw new Error(`Project directory '${resolvedDir}' does not exist or is not a directory.`);
    }

    const canonicalProjectDir = fs.realpathSync(resolvedDir);
    const port = await PreviewServer.findFreePort(preferredPort);

    this.server = http.createServer((req, res) => {
      this.handleRequest(req, res, canonicalProjectDir, entryFile);
    });

    // Track active sockets for immediate clean shutdown
    this.server.on('connection', (socket) => {
      this.activeSockets.add(socket);
      socket.on('close', () => this.activeSockets.delete(socket));
    });

    await new Promise<void>((resolve, reject) => {
      if (!this.server) return reject(new Error('Server instance is null'));
      this.server.once('error', (err) => reject(err));
      this.server.listen(port, '127.0.0.1', () => {
        resolve();
      });
    });

    const url = `http://127.0.0.1:${port}`;
    this.currentInfo = {
      port,
      url,
      projectDir: canonicalProjectDir,
      entryFile,
    };

    this.logger.info(`[PreviewServer] Artifact root: ${canonicalProjectDir}`);
    this.logger.info(`[PreviewServer] Entry point: ${entryFile}`);
    this.logger.info(`PreviewServer listening at ${url} serving ${canonicalProjectDir}`);
    return this.currentInfo;
  }

  /**
   * Stop the running preview HTTP server cleanly.
   */
  async stop(): Promise<void> {
    if (!this.server) {
      this.currentInfo = null;
      return;
    }

    const s = this.server;
    this.server = null;
    this.currentInfo = null;

    // Close all open sockets immediately
    for (const socket of this.activeSockets) {
      socket.destroy();
    }
    this.activeSockets.clear();

    await new Promise<void>((resolve) => {
      s.close(() => {
        this.logger.info('PreviewServer stopped successfully.');
        resolve();
      });
    });
  }

  /**
   * Get active preview server info, or null if stopped.
   */
  getInfo(): PreviewServerInfo | null {
    return this.currentInfo;
  }

  private handleRequest(
    req: http.IncomingMessage,
    res: http.ServerResponse,
    canonicalProjectDir: string,
    entryFile: string
  ): void {
    if (req.method !== 'GET' && req.method !== 'HEAD') {
      res.writeHead(405, { 'Content-Type': 'text/plain' });
      res.end('Method Not Allowed');
      return;
    }

    try {
      const rawUrl = req.url || '/';
      const decodedRaw = decodeURIComponent(rawUrl.split('?')[0]);

      if (decodedRaw.includes('..') || decodedRaw.includes('~')) {
        this.logger.warn(`Path traversal attempt blocked: '${rawUrl}'`);
        res.writeHead(403, { 'Content-Type': 'text/plain' });
        res.end('Forbidden: Access outside project directory is denied.');
        return;
      }

      const parsedUrl = new URL(rawUrl, `http://127.0.0.1`);
      let reqPath = decodeURIComponent(parsedUrl.pathname);

      if (reqPath === '/' || reqPath === '') {
        reqPath = '/' + entryFile;
      }

      // Safe Favicon handling: if favicon.ico is requested and missing on disk, return 204 No Content
      if (reqPath === '/favicon.ico' && !fs.existsSync(path.resolve(canonicalProjectDir, 'favicon.ico'))) {
        res.writeHead(204, {
          'Content-Type': 'image/x-icon',
          'Cache-Control': 'public, max-age=86400',
        });
        res.end();
        return;
      }

      // Strip leading slashes to resolve safely relative to projectDir
      const relativeTarget = reqPath.replace(/^\/+/, '');
      const candidatePath = path.resolve(canonicalProjectDir, relativeTarget);

      // Path traversal check 1: relative path and boundary check
      if (!isSubpathOrEqual(canonicalProjectDir, candidatePath)) {
        this.logger.warn(`Path traversal attempt blocked: '${reqPath}'`);
        res.writeHead(403, { 'Content-Type': 'text/plain' });
        res.end('Forbidden: Access outside project directory is denied.');
        return;
      }

      if (!fs.existsSync(candidatePath)) {
        res.writeHead(404, { 'Content-Type': 'text/plain' });
        res.end(`Not Found: ${reqPath}`);
        return;
      }

      let fileToServe = candidatePath;
      const stat = fs.statSync(candidatePath);

      if (stat.isDirectory()) {
        const indexInDir = path.join(candidatePath, 'index.html');
        if (fs.existsSync(indexInDir)) {
          fileToServe = indexInDir;
        } else {
          res.writeHead(404, { 'Content-Type': 'text/plain' });
          res.end('Not Found: Directory index.html missing');
          return;
        }
      }

      // Path traversal check 2: canonical realpath check (case-insensitive on Windows)
      const canonicalFile = fs.realpathSync(fileToServe);
      if (!isSubpathOrEqual(canonicalProjectDir, canonicalFile)) {
        this.logger.warn(`Symlink path traversal blocked: '${canonicalFile}'`);
        res.writeHead(403, { 'Content-Type': 'text/plain' });
        res.end('Forbidden: Access outside project directory is denied.');
        return;
      }

      this.logger.info(`[PreviewServer] Serving: ${canonicalFile}`);

      const ext = path.extname(canonicalFile).toLowerCase();
      const contentType = MIME_TYPES[ext] || 'application/octet-stream';

      const fileStat = fs.statSync(canonicalFile);
      res.writeHead(200, {
        'Content-Type': contentType,
        'Content-Length': fileStat.size,
        'Cache-Control': 'no-cache',
        'X-Content-Type-Options': 'nosniff',
      });

      if (req.method === 'HEAD') {
        res.end();
        return;
      }

      const stream = fs.createReadStream(canonicalFile);
      stream.pipe(res);
      stream.on('error', (err) => {
        this.logger.error(`Error streaming file '${canonicalFile}'`, { error: String(err) });
        if (!res.headersSent) {
          res.writeHead(500, { 'Content-Type': 'text/plain' });
        }
        res.end('Internal Server Error');
      });
    } catch (err) {
      this.logger.error('Unhandled request error', { error: String(err) });
      if (!res.headersSent) {
        res.writeHead(500, { 'Content-Type': 'text/plain' });
      }
      res.end('Internal Server Error');
    }
  }
}
